apiVersion: apps/v1
kind: Deployment
metadata:
  name: akinbuggy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akinbuggy
  template:
    metadata:
      labels:
        app: akinbuggy
    spec:
      containers:
      - name: akinbuggy
        image: 051148060727.dkr.ecr.us-west-2.amazonaws.com/akinimage
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: akinbuggy
    k8s-app: akinbuggy
  name: akinbuggy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: akinbuggy
